name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21.0.0'
          distribution: zulu
      - run: sbt compile
      - run: sbt stage
      - run: sbt scalafmtSbtCheck
      - run: sbt scalafmtCheck
      - run: sbt scalafix

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21.0.0'
          distribution: zulu
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: sbt docker:publishLocal
      - name: Rename image
        run: |
          docker image ls --format json bot-tartaglia:0.1.0-SNAPSHOT | jq -r -e '.ID' > image_id
          docker image tag "$(cat image_id)" ghcr.io/h1rono/bot-tartaglia:latest
          docker image rm bot-tartaglia:0.1.0-SNAPSHOT
          rm image_id
      - name: Save image
        run: docker save ghcr.io/h1rono/bot-tartaglia:latest > bot-tartaglia.tar
      - uses: actions/upload-artifact@v4
        with:
          name: image-archive
          path: ./bot-tartaglia.tar

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - build
      - docker-build
    if: ${{ github.ref == 'refs/heads/main' && success() }}
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: image-archive
      - name: Load image
        run: docker load < bot-tartaglia.tar
      - name: Push image
        run: docker push ghcr.io/h1rono/bot-tartaglia:latest
