name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21.0.0'
          distribution: zulu
      - run: sbt compile
      - run: sbt stage
      - run: sbt scalafmtSbtCheck
      - run: sbt scalafmtCheck
      - run: sbt scalafix

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21.0.0'
          distribution: zulu
      - uses: docker/setup-buildx-action@v3
      - run: sbt docker:publishLocal
      - run: |
          docker image ls --format json bot-tartaglia:0.1.0-SNAPSHOT | jq -r -e '.ID' > image_id
          docker image tag "$(cat image_id)" bot-tartaglia:latest
          docker image rm bot-tartaglia:0.1.0-SNAPSHOT
          rm image_id
      - run: docker save bot-tartaglia:latest > bot-tartaglia.tar
      - uses: actions/upload-artifact@v4
        with:
          name: image-archive
          path: ./bot-tartaglia.tar
